import "./globals.css";
import { NavbarRight } from "@/components/NavbarRight";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Comfy Deploy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-start">
          <div className="w-full h-18 flex items-center gap-4 p-4 border-b border-gray-200">
            <a className="font-bold text-lg hover:underline" href="/">
              Comfy Deploy
            </a>
            <NavbarRight />
            {/* <div></div> */}
          </div>
          <div className="md:px-10 px-6 w-full flex items-start">
            {children}
          </div>
          <Toaster richColors />
        </main>
      </body>
    </html>
  );
}
