# this file is a helper to run Cal.com locally
# starts a postgres instance on port 5460 to use as a local db
version: "3.6"
services:
  postgres:
    image: "postgres:15.2-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: verceldb
    ports:
      - "5480:5432"
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5481:80"
    depends_on:
      - postgres
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
    ports:
      - 4566:4566
    volumes:
      - ./aws:/etc/localstack/init/ready.d
      - ./aws:/app/web/aws